spring:
  application:
    name: stock-io-daily-processor
  data:
    mongodb:
      host: 192.168.1.123
      port: 27017
      database: company-list

cloud:
  aws:
    region:
      static: us-west-2
    
server:
  port: 8082
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true


    