spring:
  application:
    name: stock-io-daily-processor
    
server:
  port: 8081
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true
 

    