spring:
  application:
    name: stock-io-service-discovery
  cloud:
    config:
      discovery:
        enabled: true
  
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
