spring:
  application:
    name: stock-io-service-discovery
  cloud:
    config:
      discovery:
        enabled: true
 
cloud:
  aws:
    region:
      static: eu-west-1
 
server:
  port: 8761

eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:${server.port}/eureka/
