spring:
  application:
    name: stock-io-ui

server:
  port: 8080
  
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
stock-io-company-list:
  ribbon:
    eureka:
      enabled: true