spring:
  application:
    name: stock-io-company-list

cloud:
  aws:
    region:
      static: eu-west-1
        
server:
  port: 8082
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true