spring:
  application:
    name: stock-io-company-list
  data:
    mongodb:
      host: mongo
      port: 27017
      database: company-list
        
server:
  port: 8083
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true